[build]
  publish = "."
  command = ""

# Let admin.html serve directly
[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200

[[redirects]]
  from = "/admin.html"
  to = "/admin.html"
  status = 200

# SPA fallback for all other routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
